version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      # Tests
      - run:
          name: Tests
          command: npm run test
